=begin
#Scubawhere API Documentation

#This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

OpenAPI spec version: 1.0.0
Contact: bryan@scubawhere.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CustomerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CustomerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerApi' do
    it 'should create an instact of CustomerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CustomerApi)
    end
  end

  # unit tests for create_customer
  # Create a new customer
  # 
  # @param email 
  # @param firstname 
  # @param lastname 
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :birthday 
  # @option opts [Integer] :gender 
  # @option opts [String] :address_1 
  # @option opts [String] :address_2 
  # @option opts [String] :city 
  # @option opts [String] :county 
  # @option opts [String] :postcode 
  # @option opts [Integer] :country_id 
  # @option opts [String] :phone 
  # @option opts [Date] :last_dive 
  # @option opts [Integer] :number_of_dives 
  # @option opts [String] :chest_size 
  # @option opts [String] :show_size 
  # @option opts [String] :height 
  # @option opts [Array<Integer>] :certificates 
  # @return [InlineResponse20029]
  describe 'create_customer test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_customer
  # Delete a customer by ID
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2003]
  describe 'delete_customer test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for edit_customer
  # Update a customer by ID
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :email 
  # @option opts [String] :firstname 
  # @option opts [String] :lastname 
  # @option opts [Date] :birthday 
  # @option opts [Integer] :gender 
  # @option opts [String] :address_1 
  # @option opts [String] :address_2 
  # @option opts [String] :city 
  # @option opts [String] :county 
  # @option opts [String] :postcode 
  # @option opts [Integer] :country_id 
  # @option opts [String] :phone 
  # @option opts [Date] :last_dive 
  # @option opts [Integer] :number_of_dives 
  # @option opts [String] :chest_size 
  # @option opts [String] :show_size 
  # @option opts [String] :height 
  # @option opts [Array<Integer>] :certificates 
  # @return [InlineResponse20030]
  describe 'edit_customer test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_customers
  # Retrieve all customers
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<Customer>]
  describe 'get_all_customers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer
  # Retrieve a customer by ID
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id 
  # @return [InlineResponse20029]
  describe 'get_customer test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
