=begin
#Scubawhere API Documentation

#This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

OpenAPI spec version: 1.0.0
Contact: bryan@scubawhere.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PaymentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PaymentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentApi' do
    it 'should create an instact of PaymentApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PaymentApi)
    end
  end

  # unit tests for add_payment
  # Create a new payment
  # 
  # @param booking_id 
  # @param paymentgateway_id 
  # @param amount 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2011]
  describe 'add_payment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for filter_payments
  # Retrieve all payments that match a filter
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :after Date of the earliest payment
  # @option opts [Date] :before Date of the latest payment to be retrieved
  # @return [InlineResponse20035]
  describe 'filter_payments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_payments
  # Retrieve all payments made
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<Payment>]
  describe 'get_all_payments test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payment
  # Retrieve a payment by ID
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20034]
  describe 'get_payment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payment_gateways
  # Retrieve all the payment gateways
  # 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20036]
  describe 'get_payment_gateways test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
