=begin
#Scubawhere API Documentation

#This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

OpenAPI spec version: 1.0.0
Contact: bryan@scubawhere.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RefundApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RefundApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RefundApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RefundApi' do
    it 'should create an instact of RefundApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RefundApi)
    end
  end

  # unit tests for add_refund
  # Create a new refund
  # 
  # @param booking_id 
  # @param paymentgateway_id 
  # @param amount 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2012]
  describe 'add_refund test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for filter_refunds
  # Retrieve all refunds that match a filter
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Date] :after Date of the earliest payment
  # @option opts [Date] :before Date of the latest payment to be retrieved
  # @return [InlineResponse20039]
  describe 'filter_refunds test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_refunds
  # Retrieve all refunds made
  # 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20038]
  describe 'get_all_refunds test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_refund
  # Retrieve a refund by ID
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20037]
  describe 'get_refund test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
