=begin
#Scubawhere API Documentation

#This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

OpenAPI spec version: 1.0.0
Contact: bryan@scubawhere.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient

  class Company
    attr_accessor :name

    attr_accessor :description

    attr_accessor :address_1

    attr_accessor :address_2

    attr_accessor :city

    attr_accessor :county

    attr_accessor :postcode

    attr_accessor :country_id

    attr_accessor :currency_id

    attr_accessor :business_email

    attr_accessor :business_phone

    attr_accessor :vat_number

    attr_accessor :registration_number

    attr_accessor :latitude

    attr_accessor :longitude

    attr_accessor :timezone

    attr_accessor :contact

    attr_accessor :website


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'description' => :'description',
        :'address_1' => :'address_1',
        :'address_2' => :'address_2',
        :'city' => :'city',
        :'county' => :'county',
        :'postcode' => :'postcode',
        :'country_id' => :'country_id',
        :'currency_id' => :'currency_id',
        :'business_email' => :'business_email',
        :'business_phone' => :'business_phone',
        :'vat_number' => :'vat_number',
        :'registration_number' => :'registration_number',
        :'latitude' => :'latitude',
        :'longitude' => :'longitude',
        :'timezone' => :'timezone',
        :'contact' => :'contact',
        :'website' => :'website'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'name' => :'String',
        :'description' => :'String',
        :'address_1' => :'String',
        :'address_2' => :'String',
        :'city' => :'String',
        :'county' => :'String',
        :'postcode' => :'String',
        :'country_id' => :'Integer',
        :'currency_id' => :'Integer',
        :'business_email' => :'String',
        :'business_phone' => :'String',
        :'vat_number' => :'String',
        :'registration_number' => :'String',
        :'latitude' => :'Float',
        :'longitude' => :'Float',
        :'timezone' => :'String',
        :'contact' => :'String',
        :'website' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'address_1')
        self.address_1 = attributes[:'address_1']
      end

      if attributes.has_key?(:'address_2')
        self.address_2 = attributes[:'address_2']
      end

      if attributes.has_key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.has_key?(:'county')
        self.county = attributes[:'county']
      end

      if attributes.has_key?(:'postcode')
        self.postcode = attributes[:'postcode']
      end

      if attributes.has_key?(:'country_id')
        self.country_id = attributes[:'country_id']
      end

      if attributes.has_key?(:'currency_id')
        self.currency_id = attributes[:'currency_id']
      end

      if attributes.has_key?(:'business_email')
        self.business_email = attributes[:'business_email']
      end

      if attributes.has_key?(:'business_phone')
        self.business_phone = attributes[:'business_phone']
      end

      if attributes.has_key?(:'vat_number')
        self.vat_number = attributes[:'vat_number']
      end

      if attributes.has_key?(:'registration_number')
        self.registration_number = attributes[:'registration_number']
      end

      if attributes.has_key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.has_key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.has_key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.has_key?(:'contact')
        self.contact = attributes[:'contact']
      end

      if attributes.has_key?(:'website')
        self.website = attributes[:'website']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          description == o.description &&
          address_1 == o.address_1 &&
          address_2 == o.address_2 &&
          city == o.city &&
          county == o.county &&
          postcode == o.postcode &&
          country_id == o.country_id &&
          currency_id == o.currency_id &&
          business_email == o.business_email &&
          business_phone == o.business_phone &&
          vat_number == o.vat_number &&
          registration_number == o.registration_number &&
          latitude == o.latitude &&
          longitude == o.longitude &&
          timezone == o.timezone &&
          contact == o.contact &&
          website == o.website
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [name, description, address_1, address_2, city, county, postcode, country_id, currency_id, business_email, business_phone, vat_number, registration_number, latitude, longitude, timezone, contact, website].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
