=begin
#Scubawhere API Documentation

#This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 

OpenAPI spec version: 1.0.0
Contact: bryan@scubawhere.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/accommodation'
require 'swagger_client/models/addon'
require 'swagger_client/models/agent'
require 'swagger_client/models/base_price'
require 'swagger_client/models/boat'
require 'swagger_client/models/boatroom'
require 'swagger_client/models/booking'
require 'swagger_client/models/company'
require 'swagger_client/models/country'
require 'swagger_client/models/course'
require 'swagger_client/models/currency'
require 'swagger_client/models/customer'
require 'swagger_client/models/date_range'
require 'swagger_client/models/error_model'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_10'
require 'swagger_client/models/inline_response_200_11'
require 'swagger_client/models/inline_response_200_12'
require 'swagger_client/models/inline_response_200_13'
require 'swagger_client/models/inline_response_200_14'
require 'swagger_client/models/inline_response_200_15'
require 'swagger_client/models/inline_response_200_16'
require 'swagger_client/models/inline_response_200_17'
require 'swagger_client/models/inline_response_200_18'
require 'swagger_client/models/inline_response_200_19'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_20'
require 'swagger_client/models/inline_response_200_21'
require 'swagger_client/models/inline_response_200_22'
require 'swagger_client/models/inline_response_200_23'
require 'swagger_client/models/inline_response_200_24'
require 'swagger_client/models/inline_response_200_25'
require 'swagger_client/models/inline_response_200_26'
require 'swagger_client/models/inline_response_200_27'
require 'swagger_client/models/inline_response_200_28'
require 'swagger_client/models/inline_response_200_29'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_30'
require 'swagger_client/models/inline_response_200_31'
require 'swagger_client/models/inline_response_200_32'
require 'swagger_client/models/inline_response_200_33'
require 'swagger_client/models/inline_response_200_34'
require 'swagger_client/models/inline_response_200_35'
require 'swagger_client/models/inline_response_200_36'
require 'swagger_client/models/inline_response_200_37'
require 'swagger_client/models/inline_response_200_38'
require 'swagger_client/models/inline_response_200_39'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_40'
require 'swagger_client/models/inline_response_200_41'
require 'swagger_client/models/inline_response_200_42'
require 'swagger_client/models/inline_response_200_42_utilisation'
require 'swagger_client/models/inline_response_200_42_utilisation_totals'
require 'swagger_client/models/inline_response_200_43'
require 'swagger_client/models/inline_response_200_44'
require 'swagger_client/models/inline_response_200_45'
require 'swagger_client/models/inline_response_200_46'
require 'swagger_client/models/inline_response_200_47'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_200_7'
require 'swagger_client/models/inline_response_200_8'
require 'swagger_client/models/inline_response_200_9'
require 'swagger_client/models/inline_response_201'
require 'swagger_client/models/inline_response_201_1'
require 'swagger_client/models/inline_response_201_2'
require 'swagger_client/models/inline_response_201_3'
require 'swagger_client/models/inline_response_201_4'
require 'swagger_client/models/inline_response_201_5'
require 'swagger_client/models/location'
require 'swagger_client/models/package'
require 'swagger_client/models/payment'
require 'swagger_client/models/payment_gateway'
require 'swagger_client/models/pickup'
require 'swagger_client/models/refund'
require 'swagger_client/models/report_entry'
require 'swagger_client/models/report_entry_total'
require 'swagger_client/models/schedule'
require 'swagger_client/models/session'
require 'swagger_client/models/tag'
require 'swagger_client/models/ticket'
require 'swagger_client/models/timetable'
require 'swagger_client/models/training'
require 'swagger_client/models/training_session'
require 'swagger_client/models/training_session_manifest'
require 'swagger_client/models/training_session_manifest_capacity'
require 'swagger_client/models/trip'

# APIs
require 'swagger_client/api/accommodation_api'
require 'swagger_client/api/addon_api'
require 'swagger_client/api/agent_api'
require 'swagger_client/api/boat_api'
require 'swagger_client/api/boatroom_api'
require 'swagger_client/api/booking_api'
require 'swagger_client/api/class_api'
require 'swagger_client/api/classsession_api'
require 'swagger_client/api/company_api'
require 'swagger_client/api/course_api'
require 'swagger_client/api/customer_api'
require 'swagger_client/api/customers_api'
require 'swagger_client/api/location_api'
require 'swagger_client/api/locations_api'
require 'swagger_client/api/package_api'
require 'swagger_client/api/payment_api'
require 'swagger_client/api/refund_api'
require 'swagger_client/api/report_api'
require 'swagger_client/api/schedule_api'
require 'swagger_client/api/session_api'
require 'swagger_client/api/ticket_api'
require 'swagger_client/api/timetable_api'
require 'swagger_client/api/trip_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
